// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dichotomous
List dichotomous(IntegerMatrix Rdata, unsigned int dim, int model, double EMepsilon, NumericMatrix Rtheta, NumericVector Rweights, IntegerVector Rindividual_weights, IntegerVector Rclusters, NumericMatrix Rinitial_values);
RcppExport SEXP MulTRI_dichotomous(SEXP RdataSEXP, SEXP dimSEXP, SEXP modelSEXP, SEXP EMepsilonSEXP, SEXP RthetaSEXP, SEXP RweightsSEXP, SEXP Rindividual_weightsSEXP, SEXP RclustersSEXP, SEXP Rinitial_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Rdata(RdataSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type model(modelSEXP);
    Rcpp::traits::input_parameter< double >::type EMepsilon(EMepsilonSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Rtheta(RthetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rweights(RweightsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Rindividual_weights(Rindividual_weightsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Rclusters(RclustersSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Rinitial_values(Rinitial_valuesSEXP);
    __result = Rcpp::wrap(dichotomous(Rdata, dim, model, EMepsilon, Rtheta, Rweights, Rindividual_weights, Rclusters, Rinitial_values));
    return __result;
END_RCPP
}
