# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dichotomous <- function(RData, dim, model, EMepsilon, theta, weights) {
    .Call('MulTRI_dichotomous', PACKAGE = 'MulTRI', RData, dim, model, EMepsilon, theta, weights)
}

