# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dichotomous <- function(Rdata, dim, model, EMepsilon, Rtheta, Rweights, Rclusters, Rinitial_values) {
    .Call('MulTRI_dichotomous', PACKAGE = 'MulTRI', Rdata, dim, model, EMepsilon, Rtheta, Rweights, Rclusters, Rinitial_values)
}

