# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimates the parameters of a test
#'
#' @param RData Input dataset.
#' @export
dichotomous <- function(RData, dim, model, EMepsilon, wd) {
    .Call('IRTPP_dichotomous', PACKAGE = 'IRTPP', RData, dim, model, EMepsilon, wd)
}

#' Estimates the parameters of a test
#'
#' @param RData Input dataset.
#' @export
polytomous <- function(RData, dim, model, EMepsilon, wd) {
    .Call('IRTPP_polytomous', PACKAGE = 'IRTPP', RData, dim, model, EMepsilon, wd)
}

